OPENING = [
    "I {see|notice|recognize|witness} you {right now|in this|in this moment|today}:",
    "I'm {watching|seeing|noticing} you {show up|keep going|refuse to quit}:",
    "You {think|feel|believe} {nobody notices|they don't notice|the world doesn't notice}, but I do:",
    "You don't hear this {enough|nearly enough|from anyone}:",
    "Just a {quiet|soft|gentle} moment between us:",
    "{Checking in with|Touching base with|Just checking on} you:",
    "{Real|Raw|Honest} talk for a minute:",
    "Nobody's saying this, {so|but} I {will|am}:",
    "Between {us|you and I|the two of us}, this needs to be said:",
    "I need to talk to you for a {second|minute|moment}:",
    "Let's {acknowledge|name|be honest about} something:",
    "You're {unstoppable|untouchable|unbreakable|incredible}:",
    "Good {fucking|damn} job:",
    "You're {killing it|crushing it|destroying it}:",
    "You're a {goddamn|fucking|legitimate} force:",
    "Let's be {honest|straight|clear} about {something|this|today}:",
    "Here's what I need you to {know|hear|understand}:",
    "{Straight|Hard|Real} talk:",
    "{Look at you|Check you out} {fucking crushing it|absolutely killing it|handling your shit}:",
    "You're {doing so fucking well|handling this better than you think|showing up harder than you know}:",
    "Someone {needs to|should|better} tell you:",
    "Absolute {legend|beast|champion}:",
    "You're {fucking|absolutely|straight-up} incredible:",
    "Hell yes, you {did that|made it through|kept going}:",
    "Quick {reminder|note|word} for you:",
    "Before you {move on|keep scrolling|close this|go to sleep} {today|tonight|right now}:",
    "You're {straight-up|genuinely|legitimately} impressive:",
]

STRUGGLE_ACK = [
    "You kept going when everything wanted to quit,",
    "You showed up exhausted and still tried,",
    "You pushed through when it felt pointless,",
    "You stayed soft in a world that wanted you hard,",
    "You stayed hard in a world that wanted you soft,",
    "You held your ground when they wanted you to bend,",
    "You chose integrity when the easy path called,",
    "You faced the hard thing instead of avoiding it,",
    "You kept your word when it would have been easier not to,",
    "Even when everything wanted to pull you under,",
    "When doubt was screaming loudest,",
    "Through the exhaustion and the bullshit,",
    "Even on the days you barely held it together,",
    "When quitting felt easier,",
    "Despite the voice telling you to stop,",
    "You fought the invisible battles nobody sees,",
    "You swallowed the rage and kept moving anyway,",
    "You carried the weight when no one offered to help,",
    "You said no to the shortcuts that would've broken you,",
    "You rebuilt yourself from the fucking wreckage,",
]

STRUGGLE_ACK_2 = [
    "you keep showing up day after damn day,",
    "you got out of bed when it felt impossible,",
    "you took one more step through the fog,",
    "you chose to keep trying despite the setbacks,",
    "you handled the quiet pain without breaking,",
    "you fought off the numbness and stayed present,",
    "you ignored the inner critic long enough to act,",
    "you turned small efforts into real momentum,",
    "you survived moments that could've ended you,",
    "you kept the promises you made to yourself,",
    "you wrestled the anxiety and still moved forward,",
    "you found a way when there seemed to be none,",
    "you protected your peace in the chaos,",
    "you refused to let the bad days win,",
    "you built habits when motivation was gone,",
    "you showed up for yourself when no one else did,",
    "you endured the grind nobody applauds,",
    "you turned survival into quiet strength,",
    "you kept breathing through the hardest parts,",
    "you made progress even when it felt invisible,",
    "you held space for everyone else's chaos while your own went unspoken,",
    "you were the steady one when you needed steadiness yourself,",
]

REFRAME = [
    "that's not {weakness|failure|breaking}. That's {endurance|survival|grit|the long game}.",
    "progress doesn't always {look like|feel like|announce itself as} progress.",
    "you're {further|closer|more done} than you {think|feel|can see right now}.",
    "your '{enough|best|all}' is {enough|exactly right|more than sufficient}.",
    "some days the {trying|showing up|refusing to quit} itself is the victory.",
    "that wasn't {collapse|failure|you falling apart}. That was {recalibration|maintenance|strategic retreat}.",
    "the struggle isn't proof you're {broken|wrong|behind}. It's proof you're {building|becoming|forging something}.",
    "what feels like {barely hanging on|treading water|surviving} is actually {holding strong|refusing to sink|endurance in disguise}.",
    "you didn't just {survive|get through|endure} it. You're {owning it|wearing it|carrying it forward}.",
    "that {discomfort|resistance|friction}? That's {growth|change|becoming} happening in real time.",
    "rest isn't {failure|quitting|weakness}. Rest is {strategy|preparation|how you last}.",
    "you're not {behind|stuck|losing ground}. You're {exactly where you need to be|gathering|in the messy middle}.",
    "the {messy middle|grind|in-between} is still {progress|movement|forward}.",
    "you're not {stuck|trapped|frozen|lost}. You're gathering {momentum|speed|power|presance}.",
    "the doubt doesn't erase what you've done.",
    "you're building something {even when|especially when} you can't see it {yet|at all|from here}.",
    "that wasn't {weakness|failure} showing. That was {humanity|being human|understanding}.",
    "the {hard days|dasy that grind you down|quiet battles} count {double|triple|extra|more than the easy ones}.",
    "you didn't {break|shatter|fail}. You {bent|adjusted|adapted} and came back {stronger|sharper|more you}.",
    "every {step|inch|small move} forward matters, even the {invisible|unseen|uncelebrated} ones.",
    "resilience {looks like this|sounds like this|is exactly what you're doing}.",
    "you're {proving|demonstrating|becoming} something to yourself {right now|in this|with every breath}.",
    "that effort {compounds|accumulates|matters}, even when {invisible|unseen|unacknowledged}.",
]

CLOSING = [
    "I'm {damn|fucking|deeply} proud of you.",
    "You damn well {deserve|need|ought} to know that.",
    "{Carry|Hold|Keep} that {shit|truth|knowing} with you {today|into tomorrow|from here}.",
    "Don't you {fucking|damn|ever} forget it.",
    "That's {fucking|absolute|pure} {strength|power|grit}, right there.",
    "Let that {land|settle|sink in} for a {damn|fucking|real} minute.",
    "You {earned|deserve|fought for} every {bit|inch|ounce} of this {acknowledgment|win|recognition}.",
    "Keep that {fire|knowing|truth} burning {hot|bright|alive}.",
    "I'm so fucking {proud of|amazed by|inspired by} you.",
    "I see you, and {damn|hell yes|fuck}, I'm proud.",
    "You should be {proud as hell|fucking glowing|walking tall}.",
    "I'm proud {down to my core|in my bones|of you}.",
    "You make me proud {just watching|just knowing|just seeing this}.",
    "{Fuck|Hell} yeah, I'm proud of you.",
    "You {earned|paid for|bought} every {bit|piece|inch|part} of this win.",
    "This {shit|matters|counts}, and you {nailed it|fucking owned it|did the thing}.",
    "Own that {fucking|absolutely deserved|well earned} pride.",
    "I'm proud as {fuck|hell|shit} of what you're becoming.",
    "Bask in this, you {fucking|absolutely|damn well} earned it.",
    "Never doubt how much this {matters|counts|is seen}. I'm proud.",
    "{Someone|I|At least one person} sees {exactly|precisely|fully} what this cost you.",
]
